<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <PlatformTarget>AnyCPU</PlatformTarget>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="bin\**" />
    <Compile Remove="obj\**" />
    <EmbeddedResource Remove="bin\**" />
    <EmbeddedResource Remove="obj\**" />
    <None Remove="bin\**" />
    <None Remove="obj\**" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="itextsharp">
      <HintPath>Dto_dlls\itextsharp.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Office.Interop.Word">
      <HintPath>Dto_dlls\Microsoft.Office.Interop.Word.dll</HintPath>
    </Reference>
    <Reference Include="Quartz">
      <HintPath>Dto_dlls\Quartz.dll</HintPath>
    </Reference>
    <Reference Include="Spire.Doc">
      <HintPath>Dto_dlls\Spire.Doc.dll</HintPath>
    </Reference>
    <Reference Include="Spire.License">
      <HintPath>Dto_dlls\Spire.License.dll</HintPath>
    </Reference>
    <Reference Include="Spire.Pdf">
      <HintPath>Dto_dlls\Spire.Pdf.dll</HintPath>
    </Reference>
    <Reference Include="Spire.XLS">
      <HintPath>Dto_dlls\Spire.XLS.dll</HintPath>
    </Reference>
    <Reference Include="Syncfusion.DocIO.Base">
      <HintPath>Dto_dlls\Syncfusion.DocIO.Base.dll</HintPath>
    </Reference>
    <Reference Include="Syncfusion.DocToPDFConverter.Base">
      <HintPath>Dto_dlls\Syncfusion.DocToPdfConverter.Base.dll</HintPath>
    </Reference>
    <Reference Include="Syncfusion.OfficeChart.Base">
      <HintPath>Dto_dlls\Syncfusion.OfficeChart.Base.dll</HintPath>
    </Reference>
    <Reference Include="Syncfusion.Pdf.Base">
      <HintPath>Dto_dlls\Syncfusion.Pdf.Base.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
