<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <PlatformTarget>AnyCPU</PlatformTarget>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="bin\**" />
    <Compile Remove="obj\**" />
    <EmbeddedResource Remove="bin\**" />
    <EmbeddedResource Remove="obj\**" />
    <None Remove="bin\**" />
    <None Remove="obj\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="iTextSharp" Version="5.5.13.3" />
    <PackageReference Include="Spire.XLS" Version="13.4.0" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="itextsharp">
      <HintPath>Dto_dlls\itextsharp.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Office.Interop.Word">
      <HintPath>..\..\Moodies-Web\FormGeneratorDTOs\Dto_dlls\Microsoft.Office.Interop.Word.dll</HintPath>
    </Reference>
    <Reference Include="Quartz">
      <HintPath>..\..\Moodies-Web\FormGeneratorDTOs\Dto_dlls\Quartz.dll</HintPath>
    </Reference>
    <Reference Include="Spire.XLS">
      <HintPath>..\..\Moodies-Web\FormGeneratorDTOs\Dto_dlls\Spire.XLS.dll</HintPath>
    </Reference>
    <Reference Include="Syncfusion.DocIO.Base">
      <HintPath>..\..\Moodies-Web\FormGeneratorDTOs\Dto_dlls\Syncfusion.DocIO.Base.dll</HintPath>
    </Reference>
    <Reference Include="Syncfusion.DocToPDFConverter.Base">
      <HintPath>..\..\Moodies-Web\FormGeneratorDTOs\Dto_dlls\Syncfusion.DocToPdfConverter.Base.dll</HintPath>
    </Reference>
    <Reference Include="Syncfusion.OfficeChart.Base">
      <HintPath>..\..\Moodies-Web\FormGeneratorDTOs\Dto_dlls\Syncfusion.OfficeChart.Base.dll</HintPath>
    </Reference>
    <Reference Include="Syncfusion.Pdf.Base">
      <HintPath>..\..\Moodies-Web\FormGeneratorDTOs\Dto_dlls\Syncfusion.Pdf.Base.dll</HintPath>
    </Reference>
    <Reference Include="System.Configuration">
      <HintPath>C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.1\System.Configuration.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
