//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barrway.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Barrway.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activities.
        /// </summary>
        public static string Activities {
            get {
                return ResourceManager.GetString("Activities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Calendar.
        /// </summary>
        public static string Add_New_Calendar {
            get {
                return ResourceManager.GetString("Add New Calendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Company.
        /// </summary>
        public static string Add_New_Company {
            get {
                return ResourceManager.GetString("Add New Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agenda View.
        /// </summary>
        public static string Agenda_View {
            get {
                return ResourceManager.GetString("Agenda View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already have an account.
        /// </summary>
        public static string Already_have_an_account {
            get {
                return ResourceManager.GetString("Already have an account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analytics.
        /// </summary>
        public static string Analytics {
            get {
                return ResourceManager.GetString("Analytics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approvals.
        /// </summary>
        public static string Approvals {
            get {
                return ResourceManager.GetString("Approvals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B coin balance.
        /// </summary>
        public static string B_coin_balance {
            get {
                return ResourceManager.GetString("B coin balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Company dashboard.
        /// </summary>
        public static string Back_to_Company_dashboard {
            get {
                return ResourceManager.GetString("Back to Company dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barrway business.
        /// </summary>
        public static string Barrway_business {
            get {
                return ResourceManager.GetString("Barrway business", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Information.
        /// </summary>
        public static string Basic_Information {
            get {
                return ResourceManager.GetString("Basic Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking this week.
        /// </summary>
        public static string Booking_this_week {
            get {
                return ResourceManager.GetString("Booking this week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking todays.
        /// </summary>
        public static string Booking_todays {
            get {
                return ResourceManager.GetString("Booking todays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business.
        /// </summary>
        public static string Business {
            get {
                return ResourceManager.GetString("Business", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Site.
        /// </summary>
        public static string Business_Site {
            get {
                return ResourceManager.GetString("Business Site", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Users.
        /// </summary>
        public static string Business_Users {
            get {
                return ResourceManager.GetString("Business Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar.
        /// </summary>
        public static string Calendar {
            get {
                return ResourceManager.GetString("Calendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar display time.
        /// </summary>
        public static string Calendar_display_time {
            get {
                return ResourceManager.GetString("Calendar display time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar Information.
        /// </summary>
        public static string Calendar_Information {
            get {
                return ResourceManager.GetString("Calendar Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar Master.
        /// </summary>
        public static string Calendar_Master {
            get {
                return ResourceManager.GetString("Calendar Master", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar Name.
        /// </summary>
        public static string Calendar_Name {
            get {
                return ResourceManager.GetString("Calendar Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar Package.
        /// </summary>
        public static string Calendar_Package {
            get {
                return ResourceManager.GetString("Calendar Package", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar photo.
        /// </summary>
        public static string Calendar_photo {
            get {
                return ResourceManager.GetString("Calendar photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar Settings.
        /// </summary>
        public static string Calendar_Settings {
            get {
                return ResourceManager.GetString("Calendar Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check here to accept the.
        /// </summary>
        public static string Check_here_to_accept_the {
            get {
                return ResourceManager.GetString("Check here to accept the", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose category for new calendar.
        /// </summary>
        public static string Choose_category_for_new_calendar {
            get {
                return ResourceManager.GetString("Choose category for new calendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class and workshop.
        /// </summary>
        public static string Class_and_workshop {
            get {
                return ResourceManager.GetString("Class and workshop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to setup now.
        /// </summary>
        public static string Click_here_to_setup_now {
            get {
                return ResourceManager.GetString("Click here to setup now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client payment history.
        /// </summary>
        public static string Client_payment_history {
            get {
                return ResourceManager.GetString("Client payment history", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coin.
        /// </summary>
        public static string Coin {
            get {
                return ResourceManager.GetString("Coin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coins Added.
        /// </summary>
        public static string Coins_Added {
            get {
                return ResourceManager.GetString("Coins Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coins Deducted.
        /// </summary>
        public static string Coins_Deducted {
            get {
                return ResourceManager.GetString("Coins Deducted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company category.
        /// </summary>
        public static string Company_category {
            get {
                return ResourceManager.GetString("Company category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Code.
        /// </summary>
        public static string Company_Code {
            get {
                return ResourceManager.GetString("Company Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company contains.
        /// </summary>
        public static string Company_contains {
            get {
                return ResourceManager.GetString("Company contains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company description.
        /// </summary>
        public static string Company_description {
            get {
                return ResourceManager.GetString("Company description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Logo.
        /// </summary>
        public static string Company_Logo {
            get {
                return ResourceManager.GetString("Company Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Master.
        /// </summary>
        public static string Company_Master {
            get {
                return ResourceManager.GetString("Company Master", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        public static string Company_Name {
            get {
                return ResourceManager.GetString("Company Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Package.
        /// </summary>
        public static string Company_Package {
            get {
                return ResourceManager.GetString("Company Package", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Payment History.
        /// </summary>
        public static string Company_Payment_History {
            get {
                return ResourceManager.GetString("Company Payment History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Photo Album.
        /// </summary>
        public static string Company_Photo_Album {
            get {
                return ResourceManager.GetString("Company Photo Album", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Schedule.
        /// </summary>
        public static string Company_Schedule {
            get {
                return ResourceManager.GetString("Company Schedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Service.
        /// </summary>
        public static string Company_Service {
            get {
                return ResourceManager.GetString("Company Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company sub category.
        /// </summary>
        public static string Company_sub_category {
            get {
                return ResourceManager.GetString("Company sub category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete your registration.
        /// </summary>
        public static string Complete_your_registration {
            get {
                return ResourceManager.GetString("Complete your registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations.
        /// </summary>
        public static string Congratulations {
            get {
                return ResourceManager.GetString("Congratulations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact us.
        /// </summary>
        public static string Contact_us {
            get {
                return ResourceManager.GetString("Contact us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to District.
        /// </summary>
        public static string District {
            get {
                return ResourceManager.GetString("District", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have an account.
        /// </summary>
        public static string Don_t_have_an_account {
            get {
                return ResourceManager.GetString("Don\'t have an account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easiest way to organize your events and participants in one stop.
        /// </summary>
        public static string Easiest_way_to_organize_your_events_and_participants_in_one_stop {
            get {
                return ResourceManager.GetString("Easiest way to organize your events and participants in one stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eg. doctor, massage, hair cut, nail treatment.
        /// </summary>
        public static string eg__doctor__massage__hair_cut__nail_treatment {
            get {
                return ResourceManager.GetString("eg. doctor, massage, hair cut, nail treatment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eg. Party room, co-working space, dance studio.
        /// </summary>
        public static string eg__Party_room__co_working_space__dance_studio {
            get {
                return ResourceManager.GetString("eg. Party room, co-working space, dance studio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eg. Volunteering event, Dinner event.
        /// </summary>
        public static string eg__Volunteering_event__Dinner_event {
            get {
                return ResourceManager.GetString("eg. Volunteering event, Dinner event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eg. Yoga class, Piano class, Baking workshop.
        /// </summary>
        public static string eg__Yoga_class__Piano_class__Baking_workshop {
            get {
                return ResourceManager.GetString("eg. Yoga class, Piano class, Baking workshop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluation.
        /// </summary>
        public static string Evaluation {
            get {
                return ResourceManager.GetString("Evaluation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Details.
        /// </summary>
        public static string Event_Details {
            get {
                return ResourceManager.GetString("Event Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event registration.
        /// </summary>
        public static string Event_registration {
            get {
                return ResourceManager.GetString("Event registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        public static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Featured.
        /// </summary>
        public static string Featured {
            get {
                return ResourceManager.GetString("Featured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Features.
        /// </summary>
        public static string Features {
            get {
                return ResourceManager.GetString("Features", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find a service / activity in your area.
        /// </summary>
        public static string Find_a_service___activity_in_your_area {
            get {
                return ResourceManager.GetString("Find a service / activity in your area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find your service/ activity &amp; book it in one stop.
        /// </summary>
        public static string Find_your_service__activity___book_it_in_one_stop {
            get {
                return ResourceManager.GetString("Find your service/ activity & book it in one stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form description.
        /// </summary>
        public static string Form_description {
            get {
                return ResourceManager.GetString("Form description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form name.
        /// </summary>
        public static string Form_name {
            get {
                return ResourceManager.GetString("Form name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format.
        /// </summary>
        public static string Format {
            get {
                return ResourceManager.GetString("Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go.
        /// </summary>
        public static string Go {
            get {
                return ResourceManager.GetString("Go", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to dashboard.
        /// </summary>
        public static string Go_to_dashboard {
            get {
                return ResourceManager.GetString("Go to dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grand Total.
        /// </summary>
        public static string Grand_Total {
            get {
                return ResourceManager.GetString("Grand Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have your free marketing website.
        /// </summary>
        public static string Have_your_free_marketing_website {
            get {
                return ResourceManager.GetString("Have your free marketing website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How does it work.
        /// </summary>
        public static string How_does_it_work {
            get {
                return ResourceManager.GetString("How does it work", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income.
        /// </summary>
        public static string Income {
            get {
                return ResourceManager.GetString("Income", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income this week.
        /// </summary>
        public static string Income_this_week {
            get {
                return ResourceManager.GetString("Income this week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kindly complete the Step 1 - Setup your company profile.
        /// </summary>
        public static string Kindly_complete_the_Step_1___Setup_your_company_profile {
            get {
                return ResourceManager.GetString("Kindly complete the Step 1 - Setup your company profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let’s set up your company profile.
        /// </summary>
        public static string Lets_set_up_your_company_profile {
            get {
                return ResourceManager.GetString("Lets set up your company profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let’s set up your website.
        /// </summary>
        public static string Lets_set_up_your_website {
            get {
                return ResourceManager.GetString("Lets set up your website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List View.
        /// </summary>
        public static string List_View {
            get {
                return ResourceManager.GetString("List View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Master.
        /// </summary>
        public static string Location_Master {
            get {
                return ResourceManager.GetString("Location Master", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage.
        /// </summary>
        public static string Manage {
            get {
                return ResourceManager.GetString("Manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark as favorite.
        /// </summary>
        public static string Mark_as_favorite {
            get {
                return ResourceManager.GetString("Mark as favorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Market Place.
        /// </summary>
        public static string Market_Place {
            get {
                return ResourceManager.GetString("Market Place", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Attendance.
        /// </summary>
        public static string My_Attendance {
            get {
                return ResourceManager.GetString("My Attendance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Business.
        /// </summary>
        public static string My_Business {
            get {
                return ResourceManager.GetString("My Business", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Calendar.
        /// </summary>
        public static string My_Calendar {
            get {
                return ResourceManager.GetString("My Calendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Favorite.
        /// </summary>
        public static string My_Favorite {
            get {
                return ResourceManager.GetString("My Favorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Payment.
        /// </summary>
        public static string My_Payment {
            get {
                return ResourceManager.GetString("My Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My payment history.
        /// </summary>
        public static string My_payment_history {
            get {
                return ResourceManager.GetString("My payment history", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Profile.
        /// </summary>
        public static string My_Profile {
            get {
                return ResourceManager.GetString("My Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        public static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        public static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of calendars.
        /// </summary>
        public static string Number_of_calendars {
            get {
                return ResourceManager.GetString("Number of calendars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Clients.
        /// </summary>
        public static string Number_of_Clients {
            get {
                return ResourceManager.GetString("Number of Clients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Service Providers.
        /// </summary>
        public static string Number_of_Service_Provders {
            get {
                return ResourceManager.GetString("Number of Service Provders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Services.
        /// </summary>
        public static string Number_of_Services {
            get {
                return ResourceManager.GetString("Number of Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Okay.
        /// </summary>
        public static string Okay {
            get {
                return ResourceManager.GetString("Okay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One-stop event sharing booking platform.
        /// </summary>
        public static string One_stop_event_sharing_booking_platform {
            get {
                return ResourceManager.GetString("One-stop event sharing booking platform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Details.
        /// </summary>
        public static string Order_Details {
            get {
                return ResourceManager.GetString("Order Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package.
        /// </summary>
        public static string Package {
            get {
                return ResourceManager.GetString("Package", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package Details.
        /// </summary>
        public static string Package_Details {
            get {
                return ResourceManager.GetString("Package Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participant.
        /// </summary>
        public static string Participant {
            get {
                return ResourceManager.GetString("Participant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participant Master.
        /// </summary>
        public static string Participant_Master {
            get {
                return ResourceManager.GetString("Participant Master", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Particulars.
        /// </summary>
        public static string Particulars {
            get {
                return ResourceManager.GetString("Particulars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment.
        /// </summary>
        public static string Payment {
            get {
                return ResourceManager.GetString("Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Details.
        /// </summary>
        public static string Payment_Details {
            get {
                return ResourceManager.GetString("Payment Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment History.
        /// </summary>
        public static string Payment_History {
            get {
                return ResourceManager.GetString("Payment History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment method.
        /// </summary>
        public static string Payment_method {
            get {
                return ResourceManager.GetString("Payment method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Successfull.
        /// </summary>
        public static string Payment_Successfull {
            get {
                return ResourceManager.GetString("Payment Successfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Calendar Approval.
        /// </summary>
        public static string Pending_Calendar_Approval {
            get {
                return ResourceManager.GetString("Pending Calendar Approval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Company Approval.
        /// </summary>
        public static string Pending_Company_Approval {
            get {
                return ResourceManager.GetString("Pending Company Approval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo album.
        /// </summary>
        public static string Photo_album {
            get {
                return ResourceManager.GetString("Photo album", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose image files ONLY.
        /// </summary>
        public static string Please_choose_image_files_ONLY {
            get {
                return ResourceManager.GetString("Please choose image files ONLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please follow the link inside to continue.
        /// </summary>
        public static string Please_follow_the_link_inside_to_continue {
            get {
                return ResourceManager.GetString("Please follow the link inside to continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post title.
        /// </summary>
        public static string Post_title {
            get {
                return ResourceManager.GetString("Post title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post your business.
        /// </summary>
        public static string Post_your_business {
            get {
                return ResourceManager.GetString("Post your business", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pricing.
        /// </summary>
        public static string Pricing {
            get {
                return ResourceManager.GetString("Pricing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy.
        /// </summary>
        public static string Privacy {
            get {
                return ResourceManager.GetString("Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy policy.
        /// </summary>
        public static string Privacy_policy {
            get {
                return ResourceManager.GetString("Privacy policy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private office room booking.
        /// </summary>
        public static string Private_office_room_booking {
            get {
                return ResourceManager.GetString("Private office room booking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public Users.
        /// </summary>
        public static string Public_Users {
            get {
                return ResourceManager.GetString("Public Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public website link.
        /// </summary>
        public static string Public_website_link {
            get {
                return ResourceManager.GetString("Public website link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt.
        /// </summary>
        public static string Receipt {
            get {
                return ResourceManager.GetString("Receipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        public static string Registration {
            get {
                return ResourceManager.GetString("Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        public static string Remember_me {
            get {
                return ResourceManager.GetString("Remember me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove as favorite.
        /// </summary>
        public static string Remove_as_favorite {
            get {
                return ResourceManager.GetString("Remove as favorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources.
        /// </summary>
        public static string Resources {
            get {
                return ResourceManager.GetString("Resources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retype Password.
        /// </summary>
        public static string Retype_Password {
            get {
                return ResourceManager.GetString("Retype Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room rental.
        /// </summary>
        public static string Room_rental {
            get {
                return ResourceManager.GetString("Room rental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedular Form.
        /// </summary>
        public static string Schedular_Form {
            get {
                return ResourceManager.GetString("Schedular Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule.
        /// </summary>
        public static string Schedule {
            get {
                return ResourceManager.GetString("Schedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for business, service.
        /// </summary>
        public static string Search_for_business__service {
            get {
                return ResourceManager.GetString("Search for business, service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searchable in Market Place.
        /// </summary>
        public static string Searchable_in_Market_Place {
            get {
                return ResourceManager.GetString("Searchable in Market Place", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See our features.
        /// </summary>
        public static string See_our_features {
            get {
                return ResourceManager.GetString("See our features", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select a calendar.
        /// </summary>
        public static string select_a_calendar {
            get {
                return ResourceManager.GetString("select a calendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a sub-category.
        /// </summary>
        public static string Select_a_sub_category {
            get {
                return ResourceManager.GetString("Select a sub-category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your district.
        /// </summary>
        public static string Select_your_district {
            get {
                return ResourceManager.GetString("Select your district", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service.
        /// </summary>
        public static string Service {
            get {
                return ResourceManager.GetString("Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service appointment.
        /// </summary>
        public static string Service_appointment {
            get {
                return ResourceManager.GetString("Service appointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service contains.
        /// </summary>
        public static string Service_contains {
            get {
                return ResourceManager.GetString("Service contains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Master.
        /// </summary>
        public static string Service_Master {
            get {
                return ResourceManager.GetString("Service Master", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service package master.
        /// </summary>
        public static string Service_package_master {
            get {
                return ResourceManager.GetString("Service package master", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Provider Master.
        /// </summary>
        public static string Service_Provider_Master {
            get {
                return ResourceManager.GetString("Service Provider Master", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service provider work record.
        /// </summary>
        public static string Service_provider_work_record {
            get {
                return ResourceManager.GetString("Service provider work record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set up calendar.
        /// </summary>
        public static string Set_up_calendar {
            get {
                return ResourceManager.GetString("Set up calendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set up company profile.
        /// </summary>
        public static string Set_up_company_profile {
            get {
                return ResourceManager.GetString("Set up company profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set up company webiste.
        /// </summary>
        public static string Set_up_company_webiste {
            get {
                return ResourceManager.GetString("Set up company webiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set up now.
        /// </summary>
        public static string Set_up_now {
            get {
                return ResourceManager.GetString("Set up now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup your business calendar.
        /// </summary>
        public static string Setup_your_business_calendar {
            get {
                return ResourceManager.GetString("Setup your business calendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showing results for.
        /// </summary>
        public static string Showing_results_for {
            get {
                return ResourceManager.GetString("Showing results for", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out.
        /// </summary>
        public static string Sign_out {
            get {
                return ResourceManager.GetString("Sign out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slot Duration in Mins.
        /// </summary>
        public static string Slot_Duration_in_Mins {
            get {
                return ResourceManager.GetString("Slot Duration in Mins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to social media links.
        /// </summary>
        public static string social_media_links {
            get {
                return ResourceManager.GetString("social media links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort.
        /// </summary>
        public static string Sort {
            get {
                return ResourceManager.GetString("Sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step.
        /// </summary>
        public static string Step {
            get {
                return ResourceManager.GetString("Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Total.
        /// </summary>
        public static string Sub_Total {
            get {
                return ResourceManager.GetString("Sub Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subcategory.
        /// </summary>
        public static string Subcategory {
            get {
                return ResourceManager.GetString("Subcategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription.
        /// </summary>
        public static string Subscription {
            get {
                return ResourceManager.GetString("Subscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription Plans.
        /// </summary>
        public static string Subscription_Plans {
            get {
                return ResourceManager.GetString("Subscription Plans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Super admin.
        /// </summary>
        public static string Super_admin {
            get {
                return ResourceManager.GetString("Super admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Super Users.
        /// </summary>
        public static string Super_Users {
            get {
                return ResourceManager.GetString("Super Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string Tags {
            get {
                return ResourceManager.GetString("Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms &amp; condition.
        /// </summary>
        public static string Terms___condition {
            get {
                return ResourceManager.GetString("Terms & condition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This profile page will be visible by public if you choose “yes”.
        /// </summary>
        public static string This_profile_page_will_be_visible_by_public_if_you_choose_yes {
            get {
                return ResourceManager.GetString("This profile page will be visible by public if you choose yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeline Resource View.
        /// </summary>
        public static string Timeline_Resource_View {
            get {
                return ResourceManager.GetString("Timeline Resource View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transactions.
        /// </summary>
        public static string Transactions {
            get {
                return ResourceManager.GetString("Transactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trusted and enjoy by these companies.
        /// </summary>
        public static string Trusted_and_enjoy_by_these_companies {
            get {
                return ResourceManager.GetString("Trusted and enjoy by these companies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Photo.
        /// </summary>
        public static string Upload_Photo {
            get {
                return ResourceManager.GetString("Upload Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name.
        /// </summary>
        public static string User_name {
            get {
                return ResourceManager.GetString("User name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify your email.
        /// </summary>
        public static string Verify_your_email {
            get {
                return ResourceManager.GetString("Verify your email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical Resource View.
        /// </summary>
        public static string Vertical_Resource_View {
            get {
                return ResourceManager.GetString("Vertical Resource View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Way of use.
        /// </summary>
        public static string Way_of_use {
            get {
                return ResourceManager.GetString("Way of use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;ve sent a link to your email address.
        /// </summary>
        public static string We_ve_sent_a_link_to_your_email_address {
            get {
                return ResourceManager.GetString("We\'ve sent a link to your email address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        public static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website banner.
        /// </summary>
        public static string Website_banner {
            get {
                return ResourceManager.GetString("Website banner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website visits.
        /// </summary>
        public static string Website_visits {
            get {
                return ResourceManager.GetString("Website visits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to words.
        /// </summary>
        public static string words {
            get {
                return ResourceManager.GetString("words", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workload this week.
        /// </summary>
        public static string Workload_this_week {
            get {
                return ResourceManager.GetString("Workload this week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have successfully authenticated, Finish the last step of your registration.
        /// </summary>
        public static string You_have_successfully_authenticated__Finish_the_last_step_of_your_registration {
            get {
                return ResourceManager.GetString("You have successfully authenticated, Finish the last step of your registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your payment was Failed.
        /// </summary>
        public static string Your_payment_was_Failed {
            get {
                return ResourceManager.GetString("Your payment was Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your payment was successfull! This is your Payment Id.
        /// </summary>
        public static string Your_payment_was_successfull__This_is_your_Payment_Id {
            get {
                return ResourceManager.GetString("Your payment was successfull! This is your Payment Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your plans &amp; subscription.
        /// </summary>
        public static string Your_plans___subscription {
            get {
                return ResourceManager.GetString("Your plans & subscription", resourceCulture);
            }
        }
    }
}
