namespace FormGeneratorDTOs.DTOs
{
    public class AutoGeneratedPositonDTO : CommonClass
    {
        public int formId { get; set; }
        public string fieldName { get; set; }
        public string currentposition { get; set; }
        public string currentpositionFieldName { get; set; }
        public string lastposition { get; set; }
        public string lastpositionFieldName { get; set; }
        public int waitingrecords { get; set; }
        public string waitingrecordsFieldName { get; set; }

        public string autoGeneratedId { get; set; }
        public string autoGeneratedFieldName { get; set; }
        public string autoIdPrefix { get; set; }
        public string lower_range { get; set; }
        public string upper_range { get; set; }
        public int Id { get; set; }

        //public int total_records { get; set; }

    }
}
