namespace FormGeneratorDTOs.DTOs
{
    public class CallingTicketNotificationDTO : CommonClass
    {
        public int formId { get; set; }
        public int topicId { get; set; }
        public string FormTableName { get; set; }
        public int applicationId { get; set; }

        public string currentAutogeneratedId { get; set; }

        public string body { get; set; }

        public string phonenumber { get; set; }
        public string name { get; set; }

        public string QueueName { get; set; }

        public string RoomName { get; set; }

        public string currentDateTime { get; set; }
        public string fixedDate { get; set; }
        public string fixedDateTime { get; set; }

        public int currentFormType { get; set; }
    }
}
