using System;
using System.Collections.Generic;

namespace FormGeneratorDTOs.DTOs
{
    public class QueueFormDetailsDTO : CommonClass
    {
        public int formId { get; set; }
        public bool isPrimaryForm { get; set; }

        public int primaryFormId { get; set; }
        public string title { get; set; }
        public int applicationId { get; set; }
        public string applicationTitle { get; set; }
        public int topicId { get; set; }
        public int currentFormType { get; set; }

        public string CallingStatusList { get; set; }

        public string MyTicketList { get; set; }

        public string recordAccessSecurity { get; set; }

        public string formTag { get; set; }
        public Form_Roles FormRoles { get; set; }

        public QueueListDTO queueDetailBox { get; set; }
        public List<QueueListDTO> QueueList { get; set; }

    }

    public class QueueListDTO
    {
        public string currentposition { get; set; }
        public string currentpositionFieldName { get; set; }
        public string lastposition { get; set; }
        public string lastpositionFieldName { get; set; }
        public int waitingrecords { get; set; }
        public string waitingrecordsFieldName { get; set; }
        public string autoGeneratedId { get; set; }
        public string autoGeneratedFieldName { get; set; }
        public string autoIdPrefix { get; set; }
        public string lower_range { get; set; }
        public string upper_range { get; set; }
        public string waitingStatus { get; set; }
        public int total_records { get; set; }
        public string fieldName { get; set; }
        public string fieldValidationRule { get; set; }
        public string fieldType { get; set; }
        public string fieldStatusValue { get; set; }
        public int Id { get; set; }

        public string remark { get; set; }

        public string Query { get; set; }
    }


    public class QueueUserListDTO
    {
        public int topicId { get; set; }
        public string title { get; set; }
        public string currentposition { get; set; }
        public string currentpositionFieldName { get; set; }
        public string lastposition { get; set; }
        public string lastpositionFieldName { get; set; }
        public string nextposition { get; set; }
        public string nextpositionFieldName { get; set; }

        public string lastUpdatedDateTime { get; set; }

        public string formTag { get; set; }
        public int formId { get; set; }
        public int currentFormType { get; set; }

        public string listOfServing { get; set; }

        public int created_by { get; set; }

        public int Id { get; set; }
        public int userId { get; set; }

        public int action { get; set; }

        public string autoGeneratedId { get; set; }
        public string autoGeneratedFieldName { get; set; }

        public DateTime? newupdated_at { get; set; }
        public string updated_at { get; set; }
        public DateTime? newcreated_at { get; set; }
        public string created_at { get; set; }

        public string lastupdated_at { get; set; }
    }

}
